/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package genio;

/**
 *
 * @author Rubens
 */
public class Genio extends javax.swing.JFrame {

    /**
     * Creates new form Genio
     */
    public Genio() {
        initComponents();
              lblFala.setText("<html>Chute um valor entre 1 e 5</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnChutar = new javax.swing.JButton();
        num = new javax.swing.JSpinner();
        lblFala = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnChutar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnChutar.setText("Chutar");
        btnChutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChutarActionPerformed(evt);
            }
        });
        getContentPane().add(btnChutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, -1, -1));

        num.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        num.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(num, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 42, 30));

        lblFala.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblFala.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFala.setToolTipText("");
        lblFala.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblFala, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 277, 140));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/genio.png"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 300, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/balao de fala.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChutarActionPerformed
        // TODO add your handling code here:
        double random = 1+Math.random()*(6-1);
        int valor = (int) random;
        int nume = Integer.parseInt(num.getValue().toString());
        lblFala.setText((nume == valor)?"Parabens acertou":"Errou Tente denovo");
    }//GEN-LAST:event_btnChutarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Genio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Genio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Genio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Genio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Genio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChutar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblFala;
    private javax.swing.JSpinner num;
    // End of variables declaration//GEN-END:variables
}
